name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [node, python]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (Node.js)
        if: matrix.language == 'node'
        run: npm install

      - name: Install dependencies (Python)
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (Node.js)
        if: matrix.language == 'node'
        run: npm test

      - name: Run tests (Python)
        if: matrix.language == 'python'
        run: pytest
